apiVersion: v1
kind: Service
metadata:
  labels:
    application: {{ .Release.Name }}-db
  name: db
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: database
      port: {{ .Values.container.port.database }}
      targetPort: {{ .Values.container.port.database }}
  selector:
    application: {{ .Release.Name }}-db
