apiVersion: v1
kind: Service
metadata:
  labels:
    name: frontend
  name: frontend
  namespace: frontend
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 4201
  selector:
    app: frontend
