{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helloworld.serviceAccountName" . }}
  labels:
{{ include "helloworld.labels" . | indent 4 }}
{{- end -}}
